#!/bin/sh

TEMPLATE_FILE="template.c"
TARGET_FILE="a.c"
EXTRA_FILES="get_str.h"

if [ -n "$1" ]; then
    if [ -d "$1" ]; then
        echo "Error: $1 already exists"
        exit -1
    else
        mkdir $1
        cp $TEMPLATE_FILE  $1/a.c
        cp $EXTRA_FILES  $1/
    fi
else
    echo "Usage: $(basename $0) NEW_DIR"
fi
